"""
HTML Report Generator
把 CheckResult 列表輸出成簡潔的 HTML 報告。
"""

from __future__ import annotations
from datetime import datetime
from pathlib import Path

from jinja2 import Environment, BaseLoader

from circuit_checker.checker.rules import CheckResult


_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-Hant">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Circuit Checker Report</title>
<style>
  :root {
    --pass: #16a34a;
    --fail: #dc2626;
    --bg: #f8fafc;
    --card: #ffffff;
    --border: #e2e8f0;
    --text: #1e293b;
    --sub: #64748b;
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Segoe UI', system-ui, sans-serif; background: var(--bg);
         color: var(--text); padding: 2rem; }
  header { margin-bottom: 2rem; }
  header h1 { font-size: 1.5rem; font-weight: 700; }
  header p  { color: var(--sub); font-size: 0.875rem; margin-top: 0.25rem; }

  .summary {
    display: flex; gap: 1rem; margin-bottom: 2rem;
  }
  .summary-card {
    flex: 1; border-radius: 8px; padding: 1rem 1.5rem;
    border: 1px solid var(--border); background: var(--card);
  }
  .summary-card .num { font-size: 2rem; font-weight: 700; }
  .summary-card .label { font-size: 0.8rem; color: var(--sub); margin-top: 0.25rem; }
  .num.pass { color: var(--pass); }
  .num.fail { color: var(--fail); }

  .rules { display: flex; flex-direction: column; gap: 0.75rem; }
  .rule-card {
    border-radius: 8px; border: 1px solid var(--border);
    background: var(--card); overflow: hidden;
  }
  .rule-header {
    display: flex; align-items: center; gap: 0.75rem;
    padding: 0.875rem 1.25rem;
  }
  .badge {
    font-size: 0.75rem; font-weight: 700; padding: 0.2rem 0.6rem;
    border-radius: 999px; text-transform: uppercase; white-space: nowrap;
  }
  .badge.pass { background: #dcfce7; color: var(--pass); }
  .badge.fail { background: #fee2e2; color: var(--fail); }
  .rule-name  { font-weight: 600; font-size: 0.95rem; flex: 1; }
  .rule-type  { font-size: 0.75rem; color: var(--sub); font-family: monospace; }

  .rule-body { padding: 0 1.25rem 0.875rem; }
  .rule-msg  { font-size: 0.875rem; color: var(--sub); margin-bottom: 0.5rem; }
  .detail-list {
    list-style: none; font-size: 0.8rem; font-family: monospace;
    color: #475569; background: #f1f5f9; border-radius: 6px;
    padding: 0.5rem 0.75rem; line-height: 1.8;
  }
  footer {
    margin-top: 3rem; font-size: 0.75rem; color: var(--sub); text-align: center;
  }
</style>
</head>
<body>
<header>
  <h1>Circuit Checker Report</h1>
  <p>netlist: {{ netlist_dir }} &nbsp;|&nbsp; rules: {{ rules_file }} &nbsp;|&nbsp; {{ generated_at }}</p>
</header>

<div class="summary">
  <div class="summary-card">
    <div class="num">{{ total }}</div>
    <div class="label">Total Rules</div>
  </div>
  <div class="summary-card">
    <div class="num pass">{{ passed }}</div>
    <div class="label">Passed</div>
  </div>
  <div class="summary-card">
    <div class="num fail">{{ failed }}</div>
    <div class="label">Failed</div>
  </div>
</div>

<div class="rules">
{% for r in results %}
  <div class="rule-card">
    <div class="rule-header">
      <span class="badge {{ 'pass' if r.passed else 'fail' }}">
        {{ 'PASS' if r.passed else 'FAIL' }}
      </span>
      <span class="rule-name">{{ r.rule_name }}</span>
      <span class="rule-type">{{ r.rule_type }}</span>
    </div>
    {% if r.message or r.detail %}
    <div class="rule-body">
      <div class="rule-msg">{{ r.message }}</div>
      {% if r.detail %}
      <ul class="detail-list">
        {% for line in r.detail %}<li>{{ line }}</li>{% endfor %}
      </ul>
      {% endif %}
    </div>
    {% endif %}
  </div>
{% endfor %}
</div>

<footer>Generated by circuit-checker v1.0 &mdash; {{ generated_at }}</footer>
</body>
</html>
"""


def generate_html(
    results: list[CheckResult],
    netlist_dir: str,
    rules_file: str,
    output_path: str | Path,
) -> None:
    env = Environment(loader=BaseLoader())
    tmpl = env.from_string(_TEMPLATE)

    passed = sum(1 for r in results if r.passed)
    failed = len(results) - passed

    html = tmpl.render(
        results=results,
        total=len(results),
        passed=passed,
        failed=failed,
        netlist_dir=netlist_dir,
        rules_file=rules_file,
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    )

    Path(output_path).write_text(html, encoding="utf-8")
